### ISSUE TITLE
Suggestion:  Let user configure 'swing weapon' to be a keyboard key

### ISSUE THREAD

**Issue by dg1727** [neytjs/FreeMazes3D#1]
In `index.html` several of the keys are listed by using variables such as `id="keys_toggleleft"` to reflect settings made by the user in the `config.json` file.  

The `index.html` displayed value for 'swing weapon', though, is the constant text `mouse click`

It would be much more convenient if the user could set 'swing weapon' to a keyboard key.  This way, the user could keep both hands on the keyboard while playing, & wouldn't have to use the mouse.  

Many thanks in advance for considering this.

**Comment by neytjs** [comment]
Thanks for the feedback. I will add support for this in the next release.
